import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/header";
import ContextProvider from "@/context";
import { headers } from "next/headers";
import { Toaster } from "@/components/ui/sonner";


const geistSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const headersObj = await headers();
  const cookies = headersObj.get('cookie')

  return (
    <html lang="en">
      <body
        className={`${geistSans.className} antialiased bg-[#FDF2EC]`}
      >
        <ContextProvider cookies={cookies}>
          <Header />
          {children}
        </ContextProvider>
        <Toaster richColors />
      </body>
    </html>
  );
}